version: '3.9'
services:  
  site:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    container_name: apache-site
    working_dir: /var/www/html/app
    ports:
      - 8000:80    
    volumes:
      - ./app:/var/www/html/app
      - ./.docker/apache.conf:/etc/apache2/sites-enabled/000-default.conf    
    command: apache2-foreground
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1    
    tty: true
    restart: on-failure